name: Trigger auto deployment for melody-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/melody-app-AutoDeployTrigger-0954f6c0-c9b4-414d-94bd-beb1caf206ae.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MELODYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MELODYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MELODYAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: melodyreg.azurecr.io
          registryUsername: ${{ secrets.MELODYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MELODYAPP_REGISTRY_PASSWORD }}
          containerAppName: melody-app
          resourceGroup: Melody
          imageToBuild: melodyreg.azurecr.io/melody-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


